apiVersion: v1
kind: Service
metadata:
  namespace: app-ns
  name: app-loadbalancer
spec:
  selector:
    app.kubernetes.io/name: app-2049
  ports:
    - name: app-lb-port
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
